name: Angular CI

on:
  pull_request:
    branches: [main] # Adjust if your main branch has a different name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Match your local Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Run Angular tests
        run: npx ng test --watch=false --browsers=ChromeHeadless
